# Bitbucket Pipelines CI for Petstore Playwright Tests

image: node:20

pipelines:
  default:
    - step:
        name: Install and Test
        caches:
          - node
        script:
          - npm ci
          - npx playwright install --with-deps
          - npx playwright install chrome
          - npm run test:ordered
        artifacts:
          - reports/smoke/**
          - reports/positive/**
          - reports/negative/**
          - test-results/**/*.zip
          - test-results/**/*.png
          - test-results/**/*.webm
