# Bitbucket Pipelines CI for Petstore Playwright Tests

image: node:20

pipelines:
  default:
    - step:
        name: Install and Test
        caches:
          - node
        script:
          - npm ci
          - npx playwright install --with-deps
          - npm run test:ordered
        artifacts:
          - reports/smoke/**
          - reports/positive/**
          - reports/negative/**
          - tests/**/trace.zip
          - tests/**/screenshots/**/*.png
          - tests/**/videos/**/*.webm
