# GitHub Actions CI for Petstore Playwright Tests

name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests (ordered)
        run: npm run test:ordered

      - name: Upload Playwright Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-reports
          path: |
            reports/smoke
            reports/positive
            reports/negative
